---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kiqja.
--- DateTime: 2021-01-14 21:31
---

function onInit()
    onDataChanged()
end

local bDataChangedLock = false;
function onDataChanged()
    if bDataChangedLock then
        return ;
    end
    bDataChangedLock = true;
    --if not m_sType then
    createDisplay();
    --end
    if m_sType then
        updateViews();
    end
    bDataChangedLock = false;
end

function createDisplay()
    createAttack()
    createDamage()
    createAttack()
    createSave()
    createLevelCheck()
end

function createAttack()
    createControl("destruction_action_attackbutton", "attackbutton");
    createControl("destruction_action_attackviewlabel", "attackviewlabel");
    createControl("destruction_action_attackview", "attackview");
end

function createLevelCheck()
    createControl("destruction_action_levelcheckbutton", "levelcheckbutton");
    createControl("destruction_action_levelcheckviewlabel", "levelcheckviewlabel");
    createControl("destruction_action_levelcheckview", "levelcheckview");
end

function createSave()
    createControl("destruction_action_savebutton", "savebutton");
    createControl("destruction_action_saveviewlabel", "saveviewlabel");
    createControl("destruction_action_saveview", "saveview");
end

function createDamage()
    createControl("destruction_action_damagebutton", "damagebutton");
    createControl("destruction_action_damagelabel", "damagelabel");
    createControl("destruction_action_damageview", "damageview");
end

function activatePower()
    local nodeSpell = getDatabaseNode();
    if nodeSpell then
        ChatManager.Message(getDescription(), true, ActorManager.getActor("", nodeSpell.getChild(".....")));
    end
end

function usePower()
    local nodeSpell = getDatabaseNode();
    local nodeSpellClass = nodeSpell.getChild(".");
    local rActor = ActorManager.getActor("", nodeSpell.getChild("..."))

    local sMessage;

    if DB.getValue(nodeSpellClass, "castertype", "") == "points" then
        local nPP = DB.getValue(nodeSpell, ".points", 0);
        local nPPUsed = DB.getValue(nodeSpell, ".pointsused", 0);
        local nCost = DB.getValue(nodeSpell, "cost", 0);

        sMessage = DB.getValue(nodeSpell, "name", "") .. " [" .. nCost .. " PP]";
        if (nPP - nPPUsed) < nCost then
            sMessage = sMessage .. " [INSUFFICIENT PP AVAILABLE]";
        else
            nPPUsed = nPPUsed + nCost;
            DB.setValue(nodeSpell, ".pointsused", "number", nPPUsed);
        end
    else
        sMessage = DB.getValue(nodeSpell, "name", "");
    end

    ChatManager.Message(sMessage, ActorManager.isPC(rActor), rActor);
end

function onSpellCounterUpdate()
    parentcontrol.window.windowlist.window.onSpellCounterUpdate();
end